import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/app/Components/Footer";
import Header from "@/app/Components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cupcake">

      <body className="min-h-screen flex flex-col">
        <Header />
        <main className="flex-1"> {children} </main>
        <Footer />
      </body>
    </html>
  );
}
