import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/app/Components/Footer";
import Header from "@/app/Components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cupcake">
    <Header />
      <body>
        {children}
      </body>
     <Footer />
    </html>
  );
}
